/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as ReviewerRouteImport } from './routes/reviewer'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretaryIndexRouteImport } from './routes/secretary.index'
import { Route as ReviewerIndexRouteImport } from './routes/reviewer.index'
import { Route as AuthorIndexRouteImport } from './routes/author.index'
import { Route as SecretaryStatsRouteImport } from './routes/secretary.stats'
import { Route as SecretaryReviewersRouteImport } from './routes/secretary.reviewers'
import { Route as SecretaryRemindersRouteImport } from './routes/secretary.reminders'
import { Route as SecretaryPlagiarismRouteImport } from './routes/secretary.plagiarism'
import { Route as SecretaryCommunicationsRouteImport } from './routes/secretary.communications'
import { Route as ReviewerProfileRouteImport } from './routes/reviewer.profile'
import { Route as ReviewerEthicsRouteImport } from './routes/reviewer.ethics'
import { Route as AuthorSubmitRouteImport } from './routes/author.submit'
import { Route as AuthorProfileRouteImport } from './routes/author.profile'
import { Route as ReviewerInvitationsIndexRouteImport } from './routes/reviewer.invitations.index'
import { Route as ReviewerInvitationsIdRouteImport } from './routes/reviewer.invitations.$id'
import { Route as ReviewerAssignmentsIdRouteImport } from './routes/reviewer.assignments.$id'
import { Route as AuthorManuscriptsIdRouteImport } from './routes/author.manuscripts.$id'
import { Route as AuthorManuscriptsIdReviseRouteImport } from './routes/author.manuscripts.$id.revise'
import { Route as AuthorManuscriptsIdEthicsRouteImport } from './routes/author.manuscripts.$id.ethics'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewerRoute = ReviewerRouteImport.update({
  id: '/reviewer',
  path: '/reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretaryIndexRoute = SecretaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretaryRoute,
} as any)
const ReviewerIndexRoute = ReviewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewerRoute,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorRoute,
} as any)
const SecretaryStatsRoute = SecretaryStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => SecretaryRoute,
} as any)
const SecretaryReviewersRoute = SecretaryReviewersRouteImport.update({
  id: '/reviewers',
  path: '/reviewers',
  getParentRoute: () => SecretaryRoute,
} as any)
const SecretaryRemindersRoute = SecretaryRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => SecretaryRoute,
} as any)
const SecretaryPlagiarismRoute = SecretaryPlagiarismRouteImport.update({
  id: '/plagiarism',
  path: '/plagiarism',
  getParentRoute: () => SecretaryRoute,
} as any)
const SecretaryCommunicationsRoute = SecretaryCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => SecretaryRoute,
} as any)
const ReviewerProfileRoute = ReviewerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ReviewerRoute,
} as any)
const ReviewerEthicsRoute = ReviewerEthicsRouteImport.update({
  id: '/ethics',
  path: '/ethics',
  getParentRoute: () => ReviewerRoute,
} as any)
const AuthorSubmitRoute = AuthorSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorProfileRoute = AuthorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthorRoute,
} as any)
const ReviewerInvitationsIndexRoute =
  ReviewerInvitationsIndexRouteImport.update({
    id: '/invitations/',
    path: '/invitations/',
    getParentRoute: () => ReviewerRoute,
  } as any)
const ReviewerInvitationsIdRoute = ReviewerInvitationsIdRouteImport.update({
  id: '/invitations/$id',
  path: '/invitations/$id',
  getParentRoute: () => ReviewerRoute,
} as any)
const ReviewerAssignmentsIdRoute = ReviewerAssignmentsIdRouteImport.update({
  id: '/assignments/$id',
  path: '/assignments/$id',
  getParentRoute: () => ReviewerRoute,
} as any)
const AuthorManuscriptsIdRoute = AuthorManuscriptsIdRouteImport.update({
  id: '/manuscripts/$id',
  path: '/manuscripts/$id',
  getParentRoute: () => AuthorRoute,
} as any)
const AuthorManuscriptsIdReviseRoute =
  AuthorManuscriptsIdReviseRouteImport.update({
    id: '/revise',
    path: '/revise',
    getParentRoute: () => AuthorManuscriptsIdRoute,
  } as any)
const AuthorManuscriptsIdEthicsRoute =
  AuthorManuscriptsIdEthicsRouteImport.update({
    id: '/ethics',
    path: '/ethics',
    getParentRoute: () => AuthorManuscriptsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRouteWithChildren
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/reviewer': typeof ReviewerRouteWithChildren
  '/secretary': typeof SecretaryRouteWithChildren
  '/submit': typeof SubmitRoute
  '/author/profile': typeof AuthorProfileRoute
  '/author/submit': typeof AuthorSubmitRoute
  '/reviewer/ethics': typeof ReviewerEthicsRoute
  '/reviewer/profile': typeof ReviewerProfileRoute
  '/secretary/communications': typeof SecretaryCommunicationsRoute
  '/secretary/plagiarism': typeof SecretaryPlagiarismRoute
  '/secretary/reminders': typeof SecretaryRemindersRoute
  '/secretary/reviewers': typeof SecretaryReviewersRoute
  '/secretary/stats': typeof SecretaryStatsRoute
  '/author/': typeof AuthorIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/secretary/': typeof SecretaryIndexRoute
  '/author/manuscripts/$id': typeof AuthorManuscriptsIdRouteWithChildren
  '/reviewer/assignments/$id': typeof ReviewerAssignmentsIdRoute
  '/reviewer/invitations/$id': typeof ReviewerInvitationsIdRoute
  '/reviewer/invitations/': typeof ReviewerInvitationsIndexRoute
  '/author/manuscripts/$id/ethics': typeof AuthorManuscriptsIdEthicsRoute
  '/author/manuscripts/$id/revise': typeof AuthorManuscriptsIdReviseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/submit': typeof SubmitRoute
  '/author/profile': typeof AuthorProfileRoute
  '/author/submit': typeof AuthorSubmitRoute
  '/reviewer/ethics': typeof ReviewerEthicsRoute
  '/reviewer/profile': typeof ReviewerProfileRoute
  '/secretary/communications': typeof SecretaryCommunicationsRoute
  '/secretary/plagiarism': typeof SecretaryPlagiarismRoute
  '/secretary/reminders': typeof SecretaryRemindersRoute
  '/secretary/reviewers': typeof SecretaryReviewersRoute
  '/secretary/stats': typeof SecretaryStatsRoute
  '/author': typeof AuthorIndexRoute
  '/reviewer': typeof ReviewerIndexRoute
  '/secretary': typeof SecretaryIndexRoute
  '/author/manuscripts/$id': typeof AuthorManuscriptsIdRouteWithChildren
  '/reviewer/assignments/$id': typeof ReviewerAssignmentsIdRoute
  '/reviewer/invitations/$id': typeof ReviewerInvitationsIdRoute
  '/reviewer/invitations': typeof ReviewerInvitationsIndexRoute
  '/author/manuscripts/$id/ethics': typeof AuthorManuscriptsIdEthicsRoute
  '/author/manuscripts/$id/revise': typeof AuthorManuscriptsIdReviseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRouteWithChildren
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/reviewer': typeof ReviewerRouteWithChildren
  '/secretary': typeof SecretaryRouteWithChildren
  '/submit': typeof SubmitRoute
  '/author/profile': typeof AuthorProfileRoute
  '/author/submit': typeof AuthorSubmitRoute
  '/reviewer/ethics': typeof ReviewerEthicsRoute
  '/reviewer/profile': typeof ReviewerProfileRoute
  '/secretary/communications': typeof SecretaryCommunicationsRoute
  '/secretary/plagiarism': typeof SecretaryPlagiarismRoute
  '/secretary/reminders': typeof SecretaryRemindersRoute
  '/secretary/reviewers': typeof SecretaryReviewersRoute
  '/secretary/stats': typeof SecretaryStatsRoute
  '/author/': typeof AuthorIndexRoute
  '/reviewer/': typeof ReviewerIndexRoute
  '/secretary/': typeof SecretaryIndexRoute
  '/author/manuscripts/$id': typeof AuthorManuscriptsIdRouteWithChildren
  '/reviewer/assignments/$id': typeof ReviewerAssignmentsIdRoute
  '/reviewer/invitations/$id': typeof ReviewerInvitationsIdRoute
  '/reviewer/invitations/': typeof ReviewerInvitationsIndexRoute
  '/author/manuscripts/$id/ethics': typeof AuthorManuscriptsIdEthicsRoute
  '/author/manuscripts/$id/revise': typeof AuthorManuscriptsIdReviseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/author'
    | '/contact'
    | '/guidelines'
    | '/reviewer'
    | '/secretary'
    | '/submit'
    | '/author/profile'
    | '/author/submit'
    | '/reviewer/ethics'
    | '/reviewer/profile'
    | '/secretary/communications'
    | '/secretary/plagiarism'
    | '/secretary/reminders'
    | '/secretary/reviewers'
    | '/secretary/stats'
    | '/author/'
    | '/reviewer/'
    | '/secretary/'
    | '/author/manuscripts/$id'
    | '/reviewer/assignments/$id'
    | '/reviewer/invitations/$id'
    | '/reviewer/invitations/'
    | '/author/manuscripts/$id/ethics'
    | '/author/manuscripts/$id/revise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/guidelines'
    | '/submit'
    | '/author/profile'
    | '/author/submit'
    | '/reviewer/ethics'
    | '/reviewer/profile'
    | '/secretary/communications'
    | '/secretary/plagiarism'
    | '/secretary/reminders'
    | '/secretary/reviewers'
    | '/secretary/stats'
    | '/author'
    | '/reviewer'
    | '/secretary'
    | '/author/manuscripts/$id'
    | '/reviewer/assignments/$id'
    | '/reviewer/invitations/$id'
    | '/reviewer/invitations'
    | '/author/manuscripts/$id/ethics'
    | '/author/manuscripts/$id/revise'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/author'
    | '/contact'
    | '/guidelines'
    | '/reviewer'
    | '/secretary'
    | '/submit'
    | '/author/profile'
    | '/author/submit'
    | '/reviewer/ethics'
    | '/reviewer/profile'
    | '/secretary/communications'
    | '/secretary/plagiarism'
    | '/secretary/reminders'
    | '/secretary/reviewers'
    | '/secretary/stats'
    | '/author/'
    | '/reviewer/'
    | '/secretary/'
    | '/author/manuscripts/$id'
    | '/reviewer/assignments/$id'
    | '/reviewer/invitations/$id'
    | '/reviewer/invitations/'
    | '/author/manuscripts/$id/ethics'
    | '/author/manuscripts/$id/revise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthorRoute: typeof AuthorRouteWithChildren
  ContactRoute: typeof ContactRoute
  GuidelinesRoute: typeof GuidelinesRoute
  ReviewerRoute: typeof ReviewerRouteWithChildren
  SecretaryRoute: typeof SecretaryRouteWithChildren
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviewer': {
      id: '/reviewer'
      path: '/reviewer'
      fullPath: '/reviewer'
      preLoaderRoute: typeof ReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretary/': {
      id: '/secretary/'
      path: '/'
      fullPath: '/secretary/'
      preLoaderRoute: typeof SecretaryIndexRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/reviewer/': {
      id: '/reviewer/'
      path: '/'
      fullPath: '/reviewer/'
      preLoaderRoute: typeof ReviewerIndexRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/author/': {
      id: '/author/'
      path: '/'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/secretary/stats': {
      id: '/secretary/stats'
      path: '/stats'
      fullPath: '/secretary/stats'
      preLoaderRoute: typeof SecretaryStatsRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/reviewers': {
      id: '/secretary/reviewers'
      path: '/reviewers'
      fullPath: '/secretary/reviewers'
      preLoaderRoute: typeof SecretaryReviewersRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/reminders': {
      id: '/secretary/reminders'
      path: '/reminders'
      fullPath: '/secretary/reminders'
      preLoaderRoute: typeof SecretaryRemindersRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/plagiarism': {
      id: '/secretary/plagiarism'
      path: '/plagiarism'
      fullPath: '/secretary/plagiarism'
      preLoaderRoute: typeof SecretaryPlagiarismRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/communications': {
      id: '/secretary/communications'
      path: '/communications'
      fullPath: '/secretary/communications'
      preLoaderRoute: typeof SecretaryCommunicationsRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/reviewer/profile': {
      id: '/reviewer/profile'
      path: '/profile'
      fullPath: '/reviewer/profile'
      preLoaderRoute: typeof ReviewerProfileRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/ethics': {
      id: '/reviewer/ethics'
      path: '/ethics'
      fullPath: '/reviewer/ethics'
      preLoaderRoute: typeof ReviewerEthicsRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/author/submit': {
      id: '/author/submit'
      path: '/submit'
      fullPath: '/author/submit'
      preLoaderRoute: typeof AuthorSubmitRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/profile': {
      id: '/author/profile'
      path: '/profile'
      fullPath: '/author/profile'
      preLoaderRoute: typeof AuthorProfileRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/reviewer/invitations/': {
      id: '/reviewer/invitations/'
      path: '/invitations'
      fullPath: '/reviewer/invitations/'
      preLoaderRoute: typeof ReviewerInvitationsIndexRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/invitations/$id': {
      id: '/reviewer/invitations/$id'
      path: '/invitations/$id'
      fullPath: '/reviewer/invitations/$id'
      preLoaderRoute: typeof ReviewerInvitationsIdRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/reviewer/assignments/$id': {
      id: '/reviewer/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/reviewer/assignments/$id'
      preLoaderRoute: typeof ReviewerAssignmentsIdRouteImport
      parentRoute: typeof ReviewerRoute
    }
    '/author/manuscripts/$id': {
      id: '/author/manuscripts/$id'
      path: '/manuscripts/$id'
      fullPath: '/author/manuscripts/$id'
      preLoaderRoute: typeof AuthorManuscriptsIdRouteImport
      parentRoute: typeof AuthorRoute
    }
    '/author/manuscripts/$id/revise': {
      id: '/author/manuscripts/$id/revise'
      path: '/revise'
      fullPath: '/author/manuscripts/$id/revise'
      preLoaderRoute: typeof AuthorManuscriptsIdReviseRouteImport
      parentRoute: typeof AuthorManuscriptsIdRoute
    }
    '/author/manuscripts/$id/ethics': {
      id: '/author/manuscripts/$id/ethics'
      path: '/ethics'
      fullPath: '/author/manuscripts/$id/ethics'
      preLoaderRoute: typeof AuthorManuscriptsIdEthicsRouteImport
      parentRoute: typeof AuthorManuscriptsIdRoute
    }
  }
}

interface AuthorManuscriptsIdRouteChildren {
  AuthorManuscriptsIdEthicsRoute: typeof AuthorManuscriptsIdEthicsRoute
  AuthorManuscriptsIdReviseRoute: typeof AuthorManuscriptsIdReviseRoute
}

const AuthorManuscriptsIdRouteChildren: AuthorManuscriptsIdRouteChildren = {
  AuthorManuscriptsIdEthicsRoute: AuthorManuscriptsIdEthicsRoute,
  AuthorManuscriptsIdReviseRoute: AuthorManuscriptsIdReviseRoute,
}

const AuthorManuscriptsIdRouteWithChildren =
  AuthorManuscriptsIdRoute._addFileChildren(AuthorManuscriptsIdRouteChildren)

interface AuthorRouteChildren {
  AuthorProfileRoute: typeof AuthorProfileRoute
  AuthorSubmitRoute: typeof AuthorSubmitRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  AuthorManuscriptsIdRoute: typeof AuthorManuscriptsIdRouteWithChildren
}

const AuthorRouteChildren: AuthorRouteChildren = {
  AuthorProfileRoute: AuthorProfileRoute,
  AuthorSubmitRoute: AuthorSubmitRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  AuthorManuscriptsIdRoute: AuthorManuscriptsIdRouteWithChildren,
}

const AuthorRouteWithChildren =
  AuthorRoute._addFileChildren(AuthorRouteChildren)

interface ReviewerRouteChildren {
  ReviewerEthicsRoute: typeof ReviewerEthicsRoute
  ReviewerProfileRoute: typeof ReviewerProfileRoute
  ReviewerIndexRoute: typeof ReviewerIndexRoute
  ReviewerAssignmentsIdRoute: typeof ReviewerAssignmentsIdRoute
  ReviewerInvitationsIdRoute: typeof ReviewerInvitationsIdRoute
  ReviewerInvitationsIndexRoute: typeof ReviewerInvitationsIndexRoute
}

const ReviewerRouteChildren: ReviewerRouteChildren = {
  ReviewerEthicsRoute: ReviewerEthicsRoute,
  ReviewerProfileRoute: ReviewerProfileRoute,
  ReviewerIndexRoute: ReviewerIndexRoute,
  ReviewerAssignmentsIdRoute: ReviewerAssignmentsIdRoute,
  ReviewerInvitationsIdRoute: ReviewerInvitationsIdRoute,
  ReviewerInvitationsIndexRoute: ReviewerInvitationsIndexRoute,
}

const ReviewerRouteWithChildren = ReviewerRoute._addFileChildren(
  ReviewerRouteChildren,
)

interface SecretaryRouteChildren {
  SecretaryCommunicationsRoute: typeof SecretaryCommunicationsRoute
  SecretaryPlagiarismRoute: typeof SecretaryPlagiarismRoute
  SecretaryRemindersRoute: typeof SecretaryRemindersRoute
  SecretaryReviewersRoute: typeof SecretaryReviewersRoute
  SecretaryStatsRoute: typeof SecretaryStatsRoute
  SecretaryIndexRoute: typeof SecretaryIndexRoute
}

const SecretaryRouteChildren: SecretaryRouteChildren = {
  SecretaryCommunicationsRoute: SecretaryCommunicationsRoute,
  SecretaryPlagiarismRoute: SecretaryPlagiarismRoute,
  SecretaryRemindersRoute: SecretaryRemindersRoute,
  SecretaryReviewersRoute: SecretaryReviewersRoute,
  SecretaryStatsRoute: SecretaryStatsRoute,
  SecretaryIndexRoute: SecretaryIndexRoute,
}

const SecretaryRouteWithChildren = SecretaryRoute._addFileChildren(
  SecretaryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthorRoute: AuthorRouteWithChildren,
  ContactRoute: ContactRoute,
  GuidelinesRoute: GuidelinesRoute,
  ReviewerRoute: ReviewerRouteWithChildren,
  SecretaryRoute: SecretaryRouteWithChildren,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
