// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsqgwmrhgouiwopgbonw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcWd3bXJoZ291aXdvcGdib253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIwNjk4OTAsImV4cCI6MjA5NzY0NTg5MH0.ZxcFoqMh5qxrYMq27seUK-eV8Db1EKYRYCRHBcCihz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});