// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amjwfovwswthhgsvdzsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtandmb3Z3c3d0aGhnc3ZkenNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1OTM5NzYsImV4cCI6MjA5ODE2OTk3Nn0.40PyOi2YYGObywRudOZOf4WQlB6RjrP-xme92imZK4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});